name: Deploy Check
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  deploy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      - run: deno run --allow-net deploy-check.ts ${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}
